/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DayDayIdRouteImport } from './routes/day.$dayId'
import { Route as DayDayIdIndexRouteImport } from './routes/day.$dayId.index'
import { Route as DayDayIdVocabRouteImport } from './routes/day.$dayId.vocab'
import { Route as DayDayIdVerbsRouteImport } from './routes/day.$dayId.verbs'
import { Route as DayDayIdQuizRouteImport } from './routes/day.$dayId.quiz'
import { Route as DayDayIdFramesRouteImport } from './routes/day.$dayId.frames'
import { Route as DayDayIdCognatesRouteImport } from './routes/day.$dayId.cognates'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDayIdRoute = DayDayIdRouteImport.update({
  id: '/day/$dayId',
  path: '/day/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDayIdIndexRoute = DayDayIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DayDayIdRoute,
} as any)
const DayDayIdVocabRoute = DayDayIdVocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => DayDayIdRoute,
} as any)
const DayDayIdVerbsRoute = DayDayIdVerbsRouteImport.update({
  id: '/verbs',
  path: '/verbs',
  getParentRoute: () => DayDayIdRoute,
} as any)
const DayDayIdQuizRoute = DayDayIdQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => DayDayIdRoute,
} as any)
const DayDayIdFramesRoute = DayDayIdFramesRouteImport.update({
  id: '/frames',
  path: '/frames',
  getParentRoute: () => DayDayIdRoute,
} as any)
const DayDayIdCognatesRoute = DayDayIdCognatesRouteImport.update({
  id: '/cognates',
  path: '/cognates',
  getParentRoute: () => DayDayIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/review': typeof ReviewRoute
  '/stats': typeof StatsRoute
  '/day/$dayId': typeof DayDayIdRouteWithChildren
  '/day/$dayId/cognates': typeof DayDayIdCognatesRoute
  '/day/$dayId/frames': typeof DayDayIdFramesRoute
  '/day/$dayId/quiz': typeof DayDayIdQuizRoute
  '/day/$dayId/verbs': typeof DayDayIdVerbsRoute
  '/day/$dayId/vocab': typeof DayDayIdVocabRoute
  '/day/$dayId/': typeof DayDayIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/review': typeof ReviewRoute
  '/stats': typeof StatsRoute
  '/day/$dayId/cognates': typeof DayDayIdCognatesRoute
  '/day/$dayId/frames': typeof DayDayIdFramesRoute
  '/day/$dayId/quiz': typeof DayDayIdQuizRoute
  '/day/$dayId/verbs': typeof DayDayIdVerbsRoute
  '/day/$dayId/vocab': typeof DayDayIdVocabRoute
  '/day/$dayId': typeof DayDayIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/review': typeof ReviewRoute
  '/stats': typeof StatsRoute
  '/day/$dayId': typeof DayDayIdRouteWithChildren
  '/day/$dayId/cognates': typeof DayDayIdCognatesRoute
  '/day/$dayId/frames': typeof DayDayIdFramesRoute
  '/day/$dayId/quiz': typeof DayDayIdQuizRoute
  '/day/$dayId/verbs': typeof DayDayIdVerbsRoute
  '/day/$dayId/vocab': typeof DayDayIdVocabRoute
  '/day/$dayId/': typeof DayDayIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/review'
    | '/stats'
    | '/day/$dayId'
    | '/day/$dayId/cognates'
    | '/day/$dayId/frames'
    | '/day/$dayId/quiz'
    | '/day/$dayId/verbs'
    | '/day/$dayId/vocab'
    | '/day/$dayId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/review'
    | '/stats'
    | '/day/$dayId/cognates'
    | '/day/$dayId/frames'
    | '/day/$dayId/quiz'
    | '/day/$dayId/verbs'
    | '/day/$dayId/vocab'
    | '/day/$dayId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/review'
    | '/stats'
    | '/day/$dayId'
    | '/day/$dayId/cognates'
    | '/day/$dayId/frames'
    | '/day/$dayId/quiz'
    | '/day/$dayId/verbs'
    | '/day/$dayId/vocab'
    | '/day/$dayId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ReviewRoute: typeof ReviewRoute
  StatsRoute: typeof StatsRoute
  DayDayIdRoute: typeof DayDayIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$dayId': {
      id: '/day/$dayId'
      path: '/day/$dayId'
      fullPath: '/day/$dayId'
      preLoaderRoute: typeof DayDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$dayId/': {
      id: '/day/$dayId/'
      path: '/'
      fullPath: '/day/$dayId/'
      preLoaderRoute: typeof DayDayIdIndexRouteImport
      parentRoute: typeof DayDayIdRoute
    }
    '/day/$dayId/vocab': {
      id: '/day/$dayId/vocab'
      path: '/vocab'
      fullPath: '/day/$dayId/vocab'
      preLoaderRoute: typeof DayDayIdVocabRouteImport
      parentRoute: typeof DayDayIdRoute
    }
    '/day/$dayId/verbs': {
      id: '/day/$dayId/verbs'
      path: '/verbs'
      fullPath: '/day/$dayId/verbs'
      preLoaderRoute: typeof DayDayIdVerbsRouteImport
      parentRoute: typeof DayDayIdRoute
    }
    '/day/$dayId/quiz': {
      id: '/day/$dayId/quiz'
      path: '/quiz'
      fullPath: '/day/$dayId/quiz'
      preLoaderRoute: typeof DayDayIdQuizRouteImport
      parentRoute: typeof DayDayIdRoute
    }
    '/day/$dayId/frames': {
      id: '/day/$dayId/frames'
      path: '/frames'
      fullPath: '/day/$dayId/frames'
      preLoaderRoute: typeof DayDayIdFramesRouteImport
      parentRoute: typeof DayDayIdRoute
    }
    '/day/$dayId/cognates': {
      id: '/day/$dayId/cognates'
      path: '/cognates'
      fullPath: '/day/$dayId/cognates'
      preLoaderRoute: typeof DayDayIdCognatesRouteImport
      parentRoute: typeof DayDayIdRoute
    }
  }
}

interface DayDayIdRouteChildren {
  DayDayIdCognatesRoute: typeof DayDayIdCognatesRoute
  DayDayIdFramesRoute: typeof DayDayIdFramesRoute
  DayDayIdQuizRoute: typeof DayDayIdQuizRoute
  DayDayIdVerbsRoute: typeof DayDayIdVerbsRoute
  DayDayIdVocabRoute: typeof DayDayIdVocabRoute
  DayDayIdIndexRoute: typeof DayDayIdIndexRoute
}

const DayDayIdRouteChildren: DayDayIdRouteChildren = {
  DayDayIdCognatesRoute: DayDayIdCognatesRoute,
  DayDayIdFramesRoute: DayDayIdFramesRoute,
  DayDayIdQuizRoute: DayDayIdQuizRoute,
  DayDayIdVerbsRoute: DayDayIdVerbsRoute,
  DayDayIdVocabRoute: DayDayIdVocabRoute,
  DayDayIdIndexRoute: DayDayIdIndexRoute,
}

const DayDayIdRouteWithChildren = DayDayIdRoute._addFileChildren(
  DayDayIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ReviewRoute: ReviewRoute,
  StatsRoute: StatsRoute,
  DayDayIdRoute: DayDayIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
